# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += af_inet.o
obj_y += raw.o
obj_y += route.o
obj_y += protocol.o
obj_y += inetpeer.o
obj_y += igmp.o
obj_y += ip_fragment.o
obj_y += inet_fragment.o
obj_y += metrics.o

obj_y += mine.o
