#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(uart_add_one_port)
CL_MINE(uart_console_device)
CL_MINE(uart_get_rs485_mode)
CL_MINE(uart_match_port)
CL_MINE(uart_register_driver)
CL_MINE(uart_remove_one_port)
CL_MINE(uart_resume_port)
CL_MINE(uart_suspend_port)
CL_MINE(uart_unregister_driver)

CL_MINE(ioremap_prot)
CL_MINE(iounmap)
CL_MINE(__release_region)
CL_MINE(__request_region)
CL_MINE(uart_get_baud_rate)
CL_MINE(uart_get_divisor)
CL_MINE(uart_handle_cts_change)
CL_MINE(uart_handle_dcd_change)
CL_MINE(uart_insert_char)
CL_MINE(uart_parse_options)
CL_MINE(uart_set_options)
CL_MINE(uart_update_timeout)
CL_MINE(uart_write_wakeup)
