# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += vt.o
obj_y += keyboard.o
obj_y += defkeymap.o
obj_y += consolemap.o
obj_y += consolemap_deftbl.o
obj_y += vt_ioctl.o
obj_y += selection.o
obj_y += vc_screen.o

obj_y += mine.o
