# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += paging_init.o
obj_y += page_alloc.o
obj_y += memory.o
obj_y += mmzone.o
obj_y += mm_init.o
obj_y += pageattr.o
obj_y += pagewalk.o
obj_y += debug.o
obj_y += vmacache.o
