[package]
name = "find_dep"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
glob = "0.3.2"
xmas-elf = "0.9.1"
bitflags = "2.8.0"
log = "0.4.25"
env_logger = "0.11.6"
json = "0.12.4"

[profile.release]
lto = true
