#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(csum_ipv6_magic)
CL_MINE(csum_partial)
CL_MINE(csum_partial_copy_nocheck)
CL_MINE(csum_tcpudp_nofold)
CL_MINE(__dev_kfree_skb_any)
CL_MINE(dst_release)
CL_MINE(kernel_sendmsg_locked)
CL_MINE(kernel_sendpage_locked)
CL_MINE(kmem_cache_free_bulk)
CL_MINE(ksize)
CL_MINE(netdev_rx_csum_fault)
CL_MINE(net_ratelimit)
CL_MINE(page_frag_alloc)
CL_MINE(page_frag_free)
CL_MINE(skb_network_protocol)
CL_MINE(skb_set_owner_w)
CL_MINE(sk_free)
CL_MINE(sk_page_frag_refill)
CL_MINE(sock_edemux)
CL_MINE(sock_efree)
CL_MINE(sock_omalloc)
CL_MINE(sock_wfree)
CL_MINE(splice_to_pipe)
CL_MINE(tcp_get_timestamping_opt_stats)
CL_MINE(__zerocopy_sg_from_iter)
