#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(bpf_prog_change_xdp)
CL_MINE(copy_bpf_fprog_from_user)
CL_MINE(device_change_owner)
CL_MINE(device_rename)
CL_MINE(generic_splice_sendpage)
CL_MINE(poll_select_set_timeout)
CL_MINE(reuseport_detach_prog)
CL_MINE(sk_attach_bpf)
CL_MINE(sk_attach_filter)
CL_MINE(__skb_get_hash)
CL_MINE(sk_detach_filter)
CL_MINE(sk_filter_charge)
CL_MINE(sk_filter_uncharge)
CL_MINE(sk_get_filter)
CL_MINE(sk_reuseport_attach_bpf)
CL_MINE(sk_reuseport_attach_filter)
CL_MINE(sock_diag_broadcast_destroy)
CL_MINE(sock_gen_cookie)
CL_MINE(splice_to_pipe)
CL_MINE(xdp_do_generic_redirect)
CL_MINE(__zerocopy_sg_from_iter)

