#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(alloc_etherdev_mqs)
CL_MINE(eth_commit_mac_addr_change)
CL_MINE(eth_prepare_mac_addr_change)
CL_MINE(ethtool_op_get_link)
CL_MINE(ethtool_op_get_ts_info)
CL_MINE(ethtool_virtdev_set_link_ksettings)
CL_MINE(eth_validate_addr)
CL_MINE(net_failover_create)
CL_MINE(net_failover_destroy)
CL_MINE(__skb_flow_dissect)
CL_MINE(xdp_convert_zc_to_xdp_frame)
CL_MINE(xdp_do_flush)
CL_MINE(xdp_do_redirect)
CL_MINE(xdp_return_frame)
CL_MINE(xdp_return_frame_rx_napi)
CL_MINE(xdp_rxq_info_reg_mem_model)
CL_MINE(xdp_warn)
