# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += core.o
obj_y += clock.o
obj_y += debug.o
obj_y += fair.o
obj_y += deadline.o
obj_y += rt.o
obj_y += idle.o
obj_y += loadavg.o
obj_y += wait_bit.o
obj_y += wait.o
obj_y += swait.o
obj_y += completion.o
obj_y += cputime.o
obj_y += membarrier.o
