# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += blk-core.o
obj_y += blk-mq.o
obj_y += blk-mq-virtio.o
obj_y += blk-mq-cpumap.o
obj_y += blk-mq-tag.o
obj_y += blk-stat.o
obj_y += blk-settings.o
obj_y += blk-mq-sysfs.o
obj_y += blk-flush.o
obj_y += blk-ioc.o

obj_y += mine.o
