#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(blk_execute_rq)
CL_MINE(blk_mq_virtio_map_queues)
CL_MINE(blk_queue_alignment_offset)
CL_MINE(blk_queue_io_min)
CL_MINE(blk_queue_io_opt)
CL_MINE(blk_queue_logical_block_size)
CL_MINE(blk_queue_max_discard_sectors)
CL_MINE(blk_queue_max_discard_segments)
CL_MINE(blk_queue_max_hw_sectors)
CL_MINE(blk_queue_max_segments)
CL_MINE(blk_queue_max_segment_size)
CL_MINE(blk_queue_max_write_zeroes_sectors)
CL_MINE(blk_queue_physical_block_size)
CL_MINE(blk_queue_write_cache)
CL_MINE(blk_rq_map_kern)
CL_MINE(__blk_rq_map_sg)
CL_MINE(sg_init_one)
CL_MINE(sg_init_table)
CL_MINE(string_get_size)
