# SPDX-License-Identifier: GPL-2.0

target_y := bin

obj_y := head.o
obj_y += entry.o
obj_y += mm.o
obj_y += sbi.o
obj_y += traps.o
obj_y += memset.o
obj_y += memcpy.o
obj_y += string.o
obj_y += uaccess.o
obj_y += sys_ni.o
obj_y += syscalls.o
obj_y += syscall_table.o
obj_y += module_ops.o
obj_y += init.o

extra_y := startup.lds
elf_lds := startup.lds
