# SPDX-License-Identifier: GPL-2.0

always_y := exports_core_generated.h

obj_y  = main.o
obj_y += exports.o
obj_y += lang_items.o
obj_y += allocator.o

extern_obj_y  = extern_rlib/core/*.o
extern_obj_y += extern_rlib/alloc/*.o
extern_obj_y += extern_rlib/compiler_builtins/*.o
