#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(add_to_swap)
CL_MINE(blk_finish_plug)
CL_MINE(blk_start_plug)
CL_MINE(clear_page_dirty_for_io)
CL_MINE(compaction_suitable)
//CL_MINE(congestion_wait)
//CL_MINE(__delete_from_page_cache)
CL_MINE(__delete_from_swap_cache)
//CL_MINE(errseq_set)
//CL_MINE(__filemap_set_wb_err)
CL_MINE(free_unref_page_list)
//CL_MINE(I_BDEV)
CL_MINE(int_sqrt)
//CL_MINE(__lock_page)
CL_MINE(lru_add_drain)
//CL_MINE(lru_cache_add)
CL_MINE(lru_note_cost)
//CL_MINE(page_mapped)
//CL_MINE(page_mapping)
CL_MINE(page_referenced)
//CL_MINE(__put_page)
//CL_MINE(put_swap_page)
CL_MINE(reset_isolation_suitable)
CL_MINE(swap_setup)
//CL_MINE(try_to_free_buffers)
CL_MINE(try_to_free_swap)
//CL_MINE(try_to_release_page)
CL_MINE(try_to_unmap)
//CL_MINE(unlock_page)
CL_MINE(wait_iff_congested)
CL_MINE(wakeup_flusher_threads)
CL_MINE(wakeup_kcompactd)
CL_MINE(workingset_age_nonresident)
CL_MINE(workingset_eviction)
CL_MINE(zone_watermark_ok_safe)
