# SPDX-License-Identifier: GPL-2.0

target_y = startup.bin

obj_y  = boot.o
obj_y += init.o
obj_y += sbi.o
obj_y += mmu.o
obj_y += string.o
obj_y += memset.o
obj_y += memcpy.o
obj_y += load_modules.o
