#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(inet_addr_type_dev_table)
CL_MINE(inet_confirm_addr)
CL_MINE(iptunnel_metadata_reply)
CL_MINE(neigh_app_ns)
CL_MINE(neigh_carrier_down)
CL_MINE(neigh_changeaddr)
CL_MINE(neigh_connected_output)
CL_MINE(neigh_direct_output)
CL_MINE(neigh_event_ns)
CL_MINE(neigh_ifdown)
CL_MINE(neigh_lookup)
CL_MINE(neigh_remove_one)
CL_MINE(neigh_resolve_output)
CL_MINE(neigh_seq_next)
CL_MINE(neigh_seq_start)
CL_MINE(neigh_seq_stop)
CL_MINE(neigh_sysctl_register)
CL_MINE(neigh_table_init)
CL_MINE(neigh_update)
CL_MINE(pneigh_delete)
CL_MINE(pneigh_enqueue)
CL_MINE(pneigh_lookup)
