#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(inet_csk_accept)
CL_MINE(inet_csk_addr2sockaddr)
CL_MINE(inet_csk_get_port)
CL_MINE(inet_csk_prepare_forced_close)
CL_MINE(inet_csk_reqsk_queue_drop_and_put)
CL_MINE(inet_csk_route_child_sock)
CL_MINE(inet_csk_route_req)
CL_MINE(inet_csk_update_pmtu)
CL_MINE(inet_twsk_purge)
CL_MINE(inet_twsk_put)
CL_MINE(secure_tcp_seq)
CL_MINE(secure_tcp_ts_off)
CL_MINE(tcp_ca_openreq_child)
CL_MINE(tcp_check_req)
CL_MINE(tcp_child_process)
CL_MINE(tcp_cleanup_ulp)
CL_MINE(tcp_conn_request)
CL_MINE(tcp_create_openreq_child)
CL_MINE(tcp_fastopen_ctx_destroy)
CL_MINE(tcp_fastopen_defer_connect)
CL_MINE(tcp_fastopen_destroy_cipher)
CL_MINE(tcp_rcv_established)
CL_MINE(tcp_rcv_state_process)
CL_MINE(tcp_retransmit_timer)
CL_MINE(tcp_set_keepalive)
CL_MINE(tcp_simple_retransmit)
CL_MINE(tcp_syn_ack_timeout)
CL_MINE(tcp_timewait_state_process)
CL_MINE(tcp_twsk_destructor)
