#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(alloc_set_pte)
CL_MINE(__do_page_cache_readahead)
CL_MINE(errseq_check)
CL_MINE(errseq_check_and_advance)
CL_MINE(file_path)
CL_MINE(fprop_fraction_percpu)
CL_MINE(fprop_global_init)
CL_MINE(__fprop_inc_percpu_max)
CL_MINE(fprop_new_period)
CL_MINE(invalidate_inode_pages2_range)
CL_MINE(iov_iter_advance)
CL_MINE(iov_iter_copy_from_user_atomic)
CL_MINE(iov_iter_fault_in_readable)
CL_MINE(iov_iter_revert)
CL_MINE(iov_iter_single_seg_count)
CL_MINE(page_cache_async_readahead)
CL_MINE(page_cache_sync_readahead)
CL_MINE(__page_file_index)
CL_MINE(page_mkclean)
CL_MINE(pagevec_lookup_range_tag)
//CL_MINE(proc_doulongvec_minmax)
CL_MINE(rotate_reclaimable_page)
CL_MINE(sb_clear_inode_writeback)
CL_MINE(sb_mark_inode_writeback)
CL_MINE(__set_page_dirty_buffers)
CL_MINE(vfs_fsync_range)
CL_MINE(wakeup_flusher_threads_bdi)
CL_MINE(wb_start_background_writeback)
CL_MINE(workingset_refault)
CL_MINE(workingset_update_node)
