#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(account_page_cleaned)
CL_MINE(alloc_set_pte)
CL_MINE(balance_dirty_pages_ratelimited)
//CL_MINE(copy_page_to_iter)
CL_MINE(__do_page_cache_readahead)
CL_MINE(do_writepages)
CL_MINE(errseq_check)
CL_MINE(errseq_check_and_advance)
//CL_MINE(errseq_set)
CL_MINE(file_path)
//CL_MINE(I_BDEV)
CL_MINE(invalidate_inode_pages2_range)
//CL_MINE(invalidate_mapping_pages)
CL_MINE(iov_iter_advance)
CL_MINE(iov_iter_copy_from_user_atomic)
CL_MINE(iov_iter_fault_in_readable)
CL_MINE(iov_iter_revert)
CL_MINE(iov_iter_single_seg_count)
//CL_MINE(mark_page_accessed)
CL_MINE(page_cache_async_readahead)
CL_MINE(page_cache_sync_readahead)
CL_MINE(pagevec_lookup_range_tag)
//CL_MINE(__pagevec_release)
CL_MINE(page_writeback_init)
CL_MINE(rotate_reclaimable_page)
//CL_MINE(send_sig)
//CL_MINE(shmem_mapping)
CL_MINE(test_clear_page_writeback)
//CL_MINE(try_to_free_buffers)
CL_MINE(vfs_fsync_range)
CL_MINE(wait_for_stable_page)
//CL_MINE(wait_on_page_writeback)
//CL_MINE(wake_up_state)
CL_MINE(workingset_refault)
CL_MINE(workingset_update_node)
