[package]
name = "page_table"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
cfg-if = "1.0"
memory_addr = { path = "../memory_addr" }
page_table_entry = { path = "../page_table_entry" }
