#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(inet_csk_listen_stop)
CL_MINE(inet_csk_reset_keepalive_timer)
CL_MINE(reqsk_fastopen_remove)
CL_MINE(sk_stream_error)
CL_MINE(sk_stream_wait_close)
CL_MINE(sk_stream_wait_connect)
CL_MINE(sk_stream_wait_memory)
CL_MINE(sk_stream_write_space)
CL_MINE(tcp_data_ready)
CL_MINE(tcp_fastopen_get_cipher)
CL_MINE(tcp_fastopen_reset_cipher)
CL_MINE(tcp_init_xmit_timers)
CL_MINE(tcp_rate_check_app_limited)
CL_MINE(tcp_rcv_space_adjust)
CL_MINE(tcp_send_rcvq)
CL_MINE(tcp_set_ulp)
CL_MINE(tcp_time_wait)
