#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(inet_csk_listen_stop)
CL_MINE(inet_csk_reset_keepalive_timer)
CL_MINE(reqsk_fastopen_remove)
CL_MINE(sk_forced_mem_schedule)
CL_MINE(sk_stream_error)
CL_MINE(sk_stream_wait_close)
CL_MINE(sk_stream_wait_connect)
CL_MINE(sk_stream_wait_memory)
CL_MINE(sk_stream_write_space)
CL_MINE(tcp_assign_congestion_control)
CL_MINE(tcp_chrono_start)
CL_MINE(tcp_chrono_stop)
CL_MINE(tcp_clear_retrans)
CL_MINE(tcp_current_mss)
CL_MINE(tcp_cwnd_restart)
CL_MINE(tcp_data_ready)
CL_MINE(tcp_fastopen_get_cipher)
CL_MINE(tcp_fastopen_reset_cipher)
CL_MINE(tcp_init_xmit_timers)
CL_MINE(tcp_mtup_init)
CL_MINE(tcp_push_one)
CL_MINE(__tcp_push_pending_frames)
CL_MINE(tcp_rate_check_app_limited)
CL_MINE(tcp_rcv_space_adjust)
CL_MINE(tcp_register_congestion_control)
CL_MINE(__tcp_select_window)
CL_MINE(tcp_send_ack)
CL_MINE(tcp_send_active_reset)
CL_MINE(tcp_send_fin)
CL_MINE(tcp_send_rcvq)
CL_MINE(tcp_send_window_probe)
CL_MINE(tcp_set_congestion_control)
CL_MINE(tcp_set_ulp)
CL_MINE(tcp_tasklet_init)
CL_MINE(tcp_time_wait)
