# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += generic.o
obj_y += inode.o
obj_y += root.o
obj_y += base.o
obj_y += self.o
obj_y += thread_self.o
obj_y += proc_net.o
obj_y += proc_tty.o
obj_y += util.o

obj_y += mine.o
