# SPDX-License-Identifier: GPL-2.0

obj_y := fs.o
obj_y += init.o
obj_y += inode.o
obj_y += super.o
obj_y += mount.o
obj_y += namei.o
obj_y += block_dev.o
obj_y += char_dev.o
obj_y += buffer.o
obj_y += exec.o
obj_y += file_table.o
obj_y += mpage.o
obj_y += open.o
obj_y += read_write.o
obj_y += binfmt_elf.o
obj_y += file.o
