# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += fdt.o
obj_y += base.o
obj_y += property.o
obj_y += device.o
obj_y += kobj.o
obj_y += fdt_address.o
obj_y += platform.o
obj_y += base_platform.o
obj_y += address.o

obj_y += mine.o
