#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(blkdev_issue_flush)
//CL_MINE(d_add)
CL_MINE(d_alloc_cursor)
//CL_MINE(d_alloc_name)
//CL_MINE(d_genocide)
//CL_MINE(d_obtain_alias)
//CL_MINE(file_check_and_advance_wb_err)
//CL_MINE(file_write_and_wait_range)
//CL_MINE(generic_file_llseek_size)
CL_MINE(get_zeroed_page)
//CL_MINE(grab_cache_page_write_begin)
//CL_MINE(new_inode_pseudo)
//CL_MINE(nonseekable_open)
//CL_MINE(set_page_dirty)
CL_MINE(sync_inode_metadata)
CL_MINE(sync_mapping_buffers)
CL_MINE(truncate_setsize)
