# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += ctype.o
obj_y += find_bit.o
obj_y += string.o
obj_y += vsprintf.o
obj_y += siphash.o
obj_y += hexdump.o
obj_y += uaccess.o
obj_y += usercopy.o
obj_y += kstrtox.o
#obj_y += params.o
#obj_y += time.o
#obj_y += find_bit.o
