#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(add_to_swap_cache)
CL_MINE(alloc_file_pseudo)
CL_MINE(delete_from_swap_cache)
CL_MINE(d_rehash)
CL_MINE(d_tmpfile)
CL_MINE(free_swap_and_cache)
CL_MINE(generic_error_remove_page)
CL_MINE(generic_file_splice_read)
CL_MINE(get_swap_page)
CL_MINE(inode_newsize_ok)
CL_MINE(iter_file_splice_write)
CL_MINE(lookup_swap_cache)
CL_MINE(migrate_page)
CL_MINE(page_add_file_rmap)
CL_MINE(pagevec_remove_exceptionals)
CL_MINE(posix_acl_chmod)
CL_MINE(simple_acl_create)
CL_MINE(simple_set_acl)
CL_MINE(swap_cluster_readahead)
CL_MINE(swap_free)
CL_MINE(swap_shmem_alloc)
CL_MINE(swap_writepage)
CL_MINE(truncate_inode_page)
CL_MINE(user_shm_lock)
CL_MINE(user_shm_unlock)
CL_MINE(vfs_setpos)
