#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(default_llseek)
//CL_MINE(d_find_alias)
//CL_MINE(d_find_any_alias)
//CL_MINE(d_invalidate)
//CL_MINE(d_splice_alias)
//CL_MINE(generic_file_llseek)
//CL_MINE(generic_read_dir)
//CL_MINE(make_empty_dir_inode)
//CL_MINE(__mark_inode_dirty)
//CL_MINE(memdup_user_nul)
CL_MINE(name_to_int)
CL_MINE(nr_processes)
CL_MINE(proc_net_init)
CL_MINE(proc_pid_evict_inode)
CL_MINE(proc_pid_lookup)
CL_MINE(proc_pid_readdir)
CL_MINE(proc_self_init)
CL_MINE(proc_setup_self)
CL_MINE(proc_setup_thread_self)
CL_MINE(proc_sys_evict_inode)
CL_MINE(proc_sys_init)
CL_MINE(proc_thread_self_init)
CL_MINE(proc_tty_init)
//CL_MINE(put_pid_ns)
//CL_MINE(seq_open)
CL_MINE(seq_open_private)
//CL_MINE(seq_release)
CL_MINE(seq_release_private)
CL_MINE(set_proc_pid_nlink)
//CL_MINE(sync_filesystem)
