#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(access_remote_vm)
CL_MINE(cap_task_setscheduler)
CL_MINE(default_llseek)
CL_MINE(find_lock_task_mm)
CL_MINE(find_vma)
CL_MINE(__genradix_free)
CL_MINE(__genradix_ptr)
CL_MINE(__genradix_ptr_alloc)
CL_MINE(get_task_exe_file)
CL_MINE(get_task_mm)
CL_MINE(has_capability_noaudit)
CL_MINE(lookup_symbol_name)
CL_MINE(mm_access)
CL_MINE(mmput)
CL_MINE(nr_processes)
CL_MINE(oom_badness)
CL_MINE(proc_cgroup_show)
CL_MINE(process_shares_mm)
CL_MINE(proc_fd_permission)
CL_MINE(proc_pid_statm)
CL_MINE(proc_pid_status)
CL_MINE(proc_sys_evict_inode)
CL_MINE(proc_sys_init)
CL_MINE(proc_task_name)
CL_MINE(proc_tgid_stat)
CL_MINE(proc_tid_stat)
CL_MINE(stack_trace_save_tsk)
CL_MINE(task_current_syscall)

