#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(extfrag_for_order)
CL_MINE(fragmentation_index)
CL_MINE(__isolate_free_page)
CL_MINE(isolate_movable_page)
CL_MINE(migrate_pages)
CL_MINE(migrate_prep_local)
CL_MINE(putback_movable_pages)
CL_MINE(zone_watermark_ok)

CL_MINE(add_swap_count_continuation)
CL_MINE(do_page_add_anon_rmap)
CL_MINE(migration_entry_wait)
CL_MINE(munlock_vma_page)
CL_MINE(page_add_new_anon_rmap)
CL_MINE(page_remove_rmap)
CL_MINE(page_rmapping)
CL_MINE(ptep_clear_flush)
CL_MINE(swap_duplicate)
CL_MINE(tlb_flush_mmu)
CL_MINE(__tlb_remove_page_size)
CL_MINE(vma_interval_tree_iter_first)
CL_MINE(vma_interval_tree_iter_next)
