[package]
name = "axalloc"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
spinlock = { path = "../spinlock" }
memory_addr = { path = "../memory_addr" }
allocator = { path = "../allocator" }
axerror = { path = "../axerror" }
