# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += n_tty.o
obj_y += tty_io.o
obj_y += tty_mutex.o
obj_y += tty_ldisc.o
obj_y += tty_ioctl.o
obj_y += tty_jobctrl.o
obj_y += tty_buffer.o
obj_y += tty_baudrate.o
obj_y += tty_port.o
obj_y += tty_ldsem.o
