# SPDX-License-Identifier: GPL-2.0

target_y := booter.bin

obj_y := head.o
obj_y += mm_init.o
obj_y += setup.o
obj_y += sbi.o
obj_y += init.o
obj_y += load_modules.o
obj_y += memset.o
obj_y += memcpy.o
obj_y += string.o
