# SPDX-License-Identifier: GPL-2.0

PHONY := _build

include $(obj)/Makefile
include scripts/Makefile.include

_build: $(extra_y) $(_target) $(_hostprogs) $(_test)
	@:

include scripts/Makefile.library

.PHONY: $(PHONY)
