# SPDX-License-Identifier: GPL-2.0

PHONY := __modfinal

include $(obj)/Makefile

include scripts/Makefile.include

obj_y += $(obj)/$(obj).mod.o
obj_y += $(extern_obj_y)

__modfinal: $(_target)
	@:

include scripts/Makefile.library

.PHONY: $(PHONY)
