#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(bdev_read_only)
CL_MINE(bdi_alloc)
CL_MINE(bdi_register_va)
CL_MINE(blkdev_get_by_path)
CL_MINE(blkdev_put)
CL_MINE(d_genocide)
CL_MINE(emergency_thaw_bdev)
CL_MINE(free_prealloced_shrinker)
CL_MINE(fsnotify_sb_delete)
CL_MINE(group_pin_kill)
CL_MINE(invalidate_bdev)
CL_MINE(list_lru_count_one)
CL_MINE(list_lru_destroy)
CL_MINE(__list_lru_init)
CL_MINE(prealloc_shrinker)
CL_MINE(prune_dcache_sb)
CL_MINE(register_shrinker_prepared)
CL_MINE(sb_prepare_remount_readonly)
CL_MINE(sb_set_blocksize)
CL_MINE(shrink_dcache_for_umount)
CL_MINE(shrink_dcache_sb)
CL_MINE(sync_blockdev)
CL_MINE(sync_filesystem)
CL_MINE(unregister_shrinker)
