#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(anon_inode_getfile)
CL_MINE(anon_vma_fork)
CL_MINE(copy_page_range)
CL_MINE(current_is_single_threaded)
CL_MINE(do_futex)
CL_MINE(exit_aio)
CL_MINE(exit_io_context)
CL_MINE(exit_mmap)
CL_MINE(exit_shm)
CL_MINE(exit_task_namespaces)
CL_MINE(futex_exec_release)
CL_MINE(futex_exit_release)
CL_MINE(get_task_io_context)
CL_MINE(it_real_fn)
CL_MINE(__ptrace_link)
CL_MINE(put_io_context)
CL_MINE(rt_mutex_debug_task_free)
CL_MINE(sched_post_fork)
CL_MINE(signalfd_cleanup)
CL_MINE(switch_task_namespaces)
CL_MINE(unshare_nsproxy_namespaces)
CL_MINE(vma_interval_tree_insert_after)
CL_MINE(__vma_link_rb)
CL_MINE(vm_stat_account)
CL_MINE(wake_up_new_task)
