# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += mmap.o
obj_y += page-writeback.o
obj_y += context.o
obj_y += util.o
obj_y += gup.o
obj_y += swap.o
obj_y += mprotect.o
obj_y += tlbflush.o
obj_y += interval_tree.o
