# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += core.o
obj_y += property.o
obj_y += swnode.o
obj_y += map.o
obj_y += bus.o
obj_y += class.o
obj_y += firmware.o
obj_y += cpu.o
obj_y += container.o
obj_y += dd.o
obj_y += syscore.o
obj_y += driver.o

obj_y += mine.o
