#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(badblocks_show)
CL_MINE(badblocks_store)
CL_MINE(bdget)
CL_MINE(bdi_register)
CL_MINE(bdi_set_owner)
CL_MINE(blkdev_get)
CL_MINE(blk_dev_init)
CL_MINE(blk_get_queue)
CL_MINE(blk_mq_in_flight)
CL_MINE(blk_mq_in_flight_rw)
CL_MINE(blk_put_queue)
CL_MINE(blk_register_queue)
CL_MINE(blk_unregister_queue)
CL_MINE(cancel_delayed_work_sync)
CL_MINE(delete_partition)
CL_MINE(elevator_init_mq)
CL_MINE(fsync_bdev)
CL_MINE(hd_ref_init)
CL_MINE(__invalidate_device)
CL_MINE(revalidate_disk)
