# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += key.o
obj_y += keyring.o
obj_y += gc.o
obj_y += user_defined.o
obj_y += request_key_auth.o
obj_y += request_key.o
obj_y += permission.o
obj_y += process_keys.o
