#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(bio_advance)
CL_MINE(bio_clone_fast)
CL_MINE(bio_devname)
CL_MINE(bio_endio)
CL_MINE(bio_put)
CL_MINE(bioset_exit)
CL_MINE(bioset_init)
CL_MINE(blk_alloc_queue_stats)
CL_MINE(blk_free_queue_stats)
CL_MINE(blk_freeze_queue)
CL_MINE(blk_freeze_queue_start)
CL_MINE(blk_mq_alloc_request)
CL_MINE(blk_mq_exit_queue)
CL_MINE(blk_mq_flush_plug_list)
CL_MINE(blk_mq_free_request)
CL_MINE(blk_mq_request_issue_directly)
CL_MINE(blk_mq_sched_free_requests)
CL_MINE(blk_mq_submit_bio)
CL_MINE(blk_mq_wake_waiters)
CL_MINE(blk_queue_dma_alignment)
CL_MINE(blk_recalc_rq_segments)
CL_MINE(blk_rq_merge_ok)
CL_MINE(blk_rq_set_mixed_merge)
CL_MINE(blk_set_default_limits)
CL_MINE(blk_try_merge)
CL_MINE(create_task_io_context)
CL_MINE(ll_back_merge_fn)
CL_MINE(ll_front_merge_fn)
CL_MINE(rq_qos_exit)
CL_MINE(__rq_qos_merge)
