#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(blk_mq_sched_free_requests)
CL_MINE(blk_recalc_rq_segments)
CL_MINE(blk_rq_merge_ok)
CL_MINE(blk_rq_set_mixed_merge)
CL_MINE(blk_try_merge)
CL_MINE(create_task_io_context)
CL_MINE(ll_back_merge_fn)
CL_MINE(ll_front_merge_fn)
CL_MINE(rq_qos_exit)
CL_MINE(__rq_qos_merge)

CL_MINE(blk_add_timer)
CL_MINE(blk_mq_debugfs_register_hctxs)
CL_MINE(blk_mq_debugfs_unregister_hctx)
CL_MINE(blk_mq_debugfs_unregister_hctxs)
CL_MINE(blk_mq_sched_assign_ioc)
CL_MINE(__blk_mq_sched_bio_merge)
CL_MINE(blk_mq_sched_dispatch_requests)
CL_MINE(blk_mq_sched_insert_request)
CL_MINE(blk_mq_sched_insert_requests)
CL_MINE(blk_mq_sched_mark_restart_hctx)
CL_MINE(blk_mq_sched_restart)
CL_MINE(__blk_queue_split)
CL_MINE(elevator_switch_mq)
CL_MINE(list_sort)
CL_MINE(__rq_qos_cleanup)
CL_MINE(__rq_qos_done)
CL_MINE(__rq_qos_issue)
CL_MINE(__rq_qos_requeue)
CL_MINE(__rq_qos_throttle)
CL_MINE(__rq_qos_track)
CL_MINE(__rq_qos_queue_depth_changed)
