# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += blk-core.o
obj_y += blk-merge.o
obj_y += blk-settings.o
obj_y += elevator.o
obj_y += mq-deadline.o
obj_y += blk-mq.o
obj_y += blk-mq-sched.o
