# SPDX-License-Identifier: GPL-2.0

obj_y := init.o
obj_y += irqdesc.o
obj_y += proc.o
obj_y += dummychip.o
obj_y += chip.o
obj_y += irqdomain.o
obj_y += manage.o
obj_y += handle.o
obj_y += resend.o
obj_y += spurious.o
