#include <linux/types.h>
#include "../../booter/src/booter.h"

CL_MINE(__do_once_done)
CL_MINE(__do_once_start)
CL_MINE(__icmp_send)
CL_MINE(inet_get_local_port_range)
CL_MINE(inet_rcv_saddr_any)
CL_MINE(inet_rcv_saddr_equal)
CL_MINE(ip4_datagram_connect)
CL_MINE(ip4_datagram_release_cb)
CL_MINE(ip_append_data)
CL_MINE(ip_append_page)
CL_MINE(ip_check_mc_rcu)
CL_MINE(ip_cmsg_recv_offset)
CL_MINE(ip_cmsg_send)
CL_MINE(ip_flush_pending_frames)
CL_MINE(ip_generic_getfrag)
CL_MINE(__ip_make_skb)
CL_MINE(ip_make_skb)
CL_MINE(ip_mc_sf_allow)
CL_MINE(ip_mc_validate_source)
CL_MINE(ip_protocol_deliver_rcu)
CL_MINE(ip_send_skb)
CL_MINE(ipv4_pktinfo_prepare)
CL_MINE(ipv4_sk_redirect)
CL_MINE(ipv4_sk_update_pmtu)
CL_MINE(reuseport_add_sock)
CL_MINE(reuseport_alloc)
CL_MINE(reuseport_select_sock)
CL_MINE(skb_copy_and_csum_datagram_msg)
CL_MINE(__skb_try_recv_from_queue)
CL_MINE(__skb_wait_for_more_packets)
CL_MINE(__sk_queue_drop_skb)
